{% set name = "endf-parserpy" %}
{% set version = "0.14.2" %}

package:
  name: endf-parserpy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/endf_parserpy-{{ version }}.tar.gz
  sha256: 80151e594f99e7227bf87a209204f584ba0db789e035c96f32f4b3f9764d4a9e

build:
  script_env:
    #Ensure build fails if unable to build C++ modules:
    - INSTALL_ENDF_PARSERPY_CPP=yes
  entry_points:
    - endf-cli = endf_parserpy.cli.cmd:cli_interface
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11 >=2.10.0                      # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - pip
    - setuptools >=64.0.0,<77.0.0
    - pybind11 >=2.10.0
    - platformdirs >=4.3.6
    - lark >=1.0.0
  host:
    - python
    - pip
    - setuptools >=64.0.0,<77.0.0
    - pybind11 >=2.10.0
    - platformdirs >=4.3.6
    - lark >=1.0.0
  run:
    - python
    - lark >=1.0.0
    - platformdirs >=4.3.6
    - setuptools >=64.0.0,<77.0.0
    - pybind11 >=2.10.0

test:
  requires:
    - pip
  imports:
    - endf_parserpy
  commands:
    - pip check
    - endf-cli --help

about:
  home: https://github.com/iaea-nds/endf-parserpy
  summary: A Python package for reading, writing, verifying and translating ENDF-6 files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tkittel
    - gschnabel
